import { createEnv } from "@t3-oss/env-nextjs";
import * as z from "zod";

export const env = createEnv({
  server: {
    ANTHROPIC_ADMIN_API_KEY: z.string().optional(),
    BETTER_AUTH_SECRET: z.string(),
    CURSOR_API_KEY: z.string().optional(),
    ICLOUD_APPLE_ID: z.string().optional(),
    ICLOUD_DEVICE_NAME: z.string().optional(),
    ICLOUD_PASSWORD: z.string(),
    ICLOUD_WEB_SESSION_JSON: z.string(),
    LOCATION_API_TOKEN: z.string(),
    RESEND_API_KEY: z.string(),
    RESEND_SEGMENT_ID: z.string(),
    RESEND_WEBHOOK_SECRET: z.string(),
    SENTRY_PUBLIC_KEY: z.string(),
    SENTRY_OTLP_TRACES_URL: z.string(),
    SENTRY_VERCEL_LOG_DRAIN_URL: z.string(),
    SENTRY_AUTH_TOKEN: z.string(),
    SENTRY_PROJECT: z.string(),
    SENTRY_ORG: z.string(),
    TURSO_AUTH_TOKEN: z.string(),
    TURSO_DATABASE_URL: z.url(),
    NODE_ENV: z.enum(["development", "production"]).default("development"),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.url(),
    NEXT_PUBLIC_SENTRY_DSN: z.string().optional(),
  },
  runtimeEnv: {
    ANTHROPIC_ADMIN_API_KEY: process.env.ANTHROPIC_ADMIN_API_KEY,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    CURSOR_API_KEY: process.env.CURSOR_API_KEY,
    ICLOUD_APPLE_ID: process.env.ICLOUD_APPLE_ID,
    ICLOUD_DEVICE_NAME: process.env.ICLOUD_DEVICE_NAME,
    ICLOUD_PASSWORD: process.env.ICLOUD_PASSWORD,
    ICLOUD_WEB_SESSION_JSON: process.env.ICLOUD_WEB_SESSION_JSON,
    LOCATION_API_TOKEN: process.env.LOCATION_API_TOKEN,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    RESEND_SEGMENT_ID: process.env.RESEND_SEGMENT_ID,
    RESEND_WEBHOOK_SECRET: process.env.RESEND_WEBHOOK_SECRET,
    SENTRY_PUBLIC_KEY: process.env.SENTRY_PUBLIC_KEY,
    SENTRY_OTLP_TRACES_URL: process.env.SENTRY_OTLP_TRACES_URL,
    SENTRY_VERCEL_LOG_DRAIN_URL: process.env.SENTRY_VERCEL_LOG_DRAIN_URL,
    SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
    SENTRY_PROJECT: process.env.SENTRY_PROJECT,
    SENTRY_ORG: process.env.SENTRY_ORG,
    TURSO_AUTH_TOKEN: process.env.TURSO_AUTH_TOKEN,
    TURSO_DATABASE_URL: process.env.TURSO_DATABASE_URL,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NODE_ENV: process.env.NODE_ENV,
  },
});
